config/routes.rb
Rails.application.routes.draw do

  devise_for :newscasts
  root 'welcome#index'

end

app/models/newscast.rb
class Newscast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title )}
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description )}
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Castr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if alert %>
	<p class="alert">
		<%= alert %>
	</p>
<% elsif notice %>
	<p class="notice">
		<%= notice %>
	</p>
<% end %>

<header id="main_header" class="cf">
	<div class="wrapper_wide">
		<%= link_to "NewsCast", root_path, id: "logo" %>
		<nav>
			<ul>
				<% unless newscast_signed_in? %>
					<li><a href="#">Explore</a></li>
					<li><%= link_to "Sign In", new_newscast_session_path  %></li>
					<li><%= link_to "Cast Something", new_newscast_registration_path %></li>
				<% else %>
					<li><a href="#">Dashboard</a></li>
					<li><a href="#">Explore</a></li>
					<li><%= link_to "Sign Out", destroy_newscast_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div><!-- end wrapper -->
</header>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="background">
	<header class="cf">
		<div class="wrapper_wide">
			<a href="#" id="logo">NewsCast.fm</a>
			<nav>
				<ul>
				<% unless newscast_signed_in? %>
					<li><a href="#">Explore</a></li>
					<li><%= link_to "Sign In", new_newscast_session_path  %></li>
					<li><%= link_to "Cast Something", new_newscast_registration_path %></li>
				<% else %>
					<li><a href="#">Dashboard</a></li>
					<li><a href="#">Explore</a></li>
					<li><%= link_to "Sign Out", destroy_newscast_session_path, method: :delete %></li>
				<% end %>
				</ul>
			</nav>
		</div><!-- end wrapper -->
	</header>
	<div class="wrapper_skinny">
		<h1>Stay Informed </br> Keep up with local happenings </br> from local casters</h1>
		<%= link_to "Cast Something", new_newscast_registration_path, class: "button button_highlight" %>
		<a href="#" class="button button_white">Explore</a>
	</div><!-- end wrapper_skinny -->
</div>